baseURL: "https://hugo.dedov.ws/"
# paginate: 5
theme: PaperMod

languageCode: ru
defaultContentLanguage: ru
# defaultContentLanguageInSubdir: true

diagram: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# canonifyURLs: true
# relativeURLs: true

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

pygmentsUseClasses: true

taxonomies:
  category: categories
  tag: tags
  series: series
# permalinks:
#   page:
#     posts: /articles/:year/:month/:slug/
#     tutorials: /training/:slug/
#   section:
#     posts: /articles/
#     tutorials: /training/

# Местоположение контента, шаблонов и т. д.
# publishdir: docs
# contentDir: content
# layoutDir: layouts
# staticDir:
#   - static
#   - static/images

# services:
#   disqus:
#     shortname: SergeyDedov

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search