baseURL: "https://hugo.dedov.ws/"
paginate: 10
theme: PaperMod

languageCode: ru
defaultContentLanguage: ru
# defaultContentLanguageInSubdir: true

diagram: true
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# canonifyURLs: true
# relativeURLs: true

services:
  googleAnalytics:
    ID: UA-52691292-1
  disqus:
    shortname: SergeyDedov

minify:
  disableXML: true
  minifyOutput: true

pygmentsUseClasses: true

taxonomies:
  category: categories
  tag: tags
  series: series
# permalinks:
#   page:
#     posts: /articles/:year/:month/:slug/
#     tutorials: /training/:slug/
#   section:
#     posts: /articles/
#     tutorials: /training/

# Местоположение контента, шаблонов и т. д.
# publishdir: docs
# contentDir: content
# layoutDir: layouts
# staticDir:
#   - static
#   - static/images

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

# security:
#   enableInlineShortcodes: false
#   exec:
#     allow:
#       - ^dart-sass-embedded$
#       - ^go$
#       - ^npx$
#       - ^postcss$
#       - ^pandoc$
#       - ^nvim$
#     osEnv:
#       - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
#   funcs:
#     getenv:
#       - ^HUGO_
#   http:
#     methods:
#       - (?i)GET|POST
#     urls:
#       - .*
