ru:
  title: Сергей ДЕДОВ
  # contentDir: content/post/ru
  # disabled: true
  languageCode: ru-Ru
  languageName: Русский
  weight: 1
  params:
    author: Сергей ДЕДОВ
    profileMode:
      enabled: true # needs to be explicitly set
      title: Сергей ДЕДОВ
      subtitle: Взращивая бизнес
      imageUrl: ../assets/media/icon.png
      imageWidth: 200
      imageHeight: 200
      imageTitle: my image
      buttons:
        - name: Блог
          url: posts
        - name: Темы
          url: tags
        # - name: Поиск
        #   url: /search
        # - name: Архив
        #   url: archives
### English
en:
  title: Sergey DEDOV
  # contentDir: content/post/en
  # disabled: true
  languageCode: en-US
  languageName: English
  weight: 2
  params:
    author: Sergey DEDOV
    profileMode:
      enabled: true # needs to be explicitly set
      title: Sergey DEDOV
      subtitle: Growing a business
      imageUrl: ../assets/media/icon.png
      imageWidth: 200
      imageHeight: 200
      imageTitle: my image
      buttons:
        - name: Posts
          url: posts
        - name: Tags
          url: tags
        # - name: Archive
        #   url: archives