# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# defaultMarkdownHandler: pandoc

highlight:
  noClasses: false
  # anchorLineNos: true
  # lineAnchors:
  codeFences: true
  guessSyntax: true
  # lineNos: true
  # lineNoStart: 1
  style: monokai
  hl_Lines:
  lineNumbersInTable: true
  noHl: false
  tabWidth: 4

# goldmark:
#   parser:
#     wrapStandAloneImageWithinParagraph: false
#     attribute:
#       block: true