env: production # to enable google analytics, opengraph, twitter-cards and schema.
copyright: Copyright © 2000-2023 by [Sergey DEDOV](https://dedov.ws)
title: Sergey DEDOV | Real Estate Expert
description: Sergey DEDOV Personal site
keywords: [управление проектами, строительство, планирование, организация, контроль, сроки, бюджет, качество]
# copyright: \@ Sergey DEDOV, 2023
# author: ["Me", "You"] # multiple authors
images: [SD_photo.jpeg]
DateFormat: "2/01/2006"
defaultTheme: auto # dark, light
disableThemeToggle: false
ShowReadingTime: true
ShowShareButtons: true
ShareButtons:
  - linkedin
  - telegram
  - whatsapp
  - facebook
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowWordCount: true
ShowRssButtonInSectionTermList: true
UseHugoToc: true
disableSpecial1stPost: false
disableScrollToTop: false
comments: true
hidemeta: false
hideSummary: false
showtoc: true
tocopen: false
readMore: true
readNextPosts: 5
tocWordCount: 300 # ...when a post is longer than 300 words

assets:
  favicon: true
  # disableHLJS: true # to disable highlight.js
  # disableFingerprinting: true
  favicon: icon.png
  # favicon16x16: "<link / abs url>"
  # favicon32x32: "<link / abs url>"
  # apple_touch_icon: "<link / abs url>"
  # safari_pinned_tab: "<link / abs url>"

# home-info mode
homeInfoParams:
  Title: "Приветствую на моей страничке \U0001F44B"
  Content: Добро пожаловать!!!

socialIcons:
  # - name: CV
  #   url: /CV/
  - name: telegram
    url: https://t.me/kiiit
  - name: phone
    url: tel:+79999000000
  - name: email
    url: mailto:sergey@dedov.ws
  - name: facebook
    url: https://www.facebook.com/Dedov.Sergey/
  - name: LinkedIn
    url: https://www.linkedin.com/in/dedovsergey/

analytics:
  google:
    SiteVerificationTag: "XYZabc"
  bing:
    SiteVerificationTag: "XYZabc"
  yandex:
    SiteVerificationTag: "XYZabc"

cover:
  hidden: false # hide everywhere but not in structured data
  hiddenInList: true # hide on list pages and home
  # hiddenInSingle: true # hide on single page
  # linkFullImages: true

schema:
  publisherType: Organization

# editPost:
#   URL: "https://hugo.dedov.ws/content"
#   Text: "Внести изменения" # edit text
#   appendFilePath: true # to append file path to Edit link

# for search
# https://fusejs.io/api/options.html
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]