main:
  - identifier: home
    name: Home
    pageRef: /
    weight: 1
  - identifier: collab
    name: Collaborations
    pageRef: /collab
    weight: 2
  - identifier: projects
    name: Projects
    pageRef: /projects
    weight: 5
  # - identifier: posts
  #   name: Posts
  #   pageRef: /posts
  #   weight: 5
  - identifier: pages
    name: Science
    pageRef: /articles
    weight: 10
  # - identifier: tags
  #   name: Tags
  #   pageRef: /tags
  #   weight: 20
  - identifier: CV
    name: CV
    pageRef: /CV/cv
    weight: 50
  - identifier: search
    name: Search
    url: /search
    weight: 40
  # - name: Hugo
  #   rel: external
  #   # pre: <i class="fa fa-heart"></i>
  #   url: https://gohugo.io/
  #   weight: 30
footer:
  - name: Terms
    pageRef: /terms
    weight: 10
  - name: Privacy
    pageRef: /privacy
    weight: 20
