main:
  - identifier: home
    name: Домой
    pageRef: /
    weight: 1
  - identifier: collab
    name: Сотрудничество
    pageRef: /collab
    weight: 3
  - identifier: posts
    name: Новости
    pageRef: /posts
    weight: 2
  - identifier: categories
    name: Статьи
    pageRef: /categories/статья/
    weight: 10
  - identifier: tags
    name: Темы
    pageRef: /tags
    weight: 20
  # - name: Hugo
  #   rel: external
  #   # pre: <i class="fa fa-heart"></i>
  #   url: https://gohugo.io/
  #   weight: 30
footer:
  - name: Terms
    pageRef: /terms
    weight: 10
  - name: Privacy
    pageRef: /privacy
    weight: 20
